name: Codecov

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Write GPG key
        run: echo ${{ GPG_PRIVATE_KEY }} > gpg-private.key
      - name: Import GPG key
        run: gpg --import gpg-private.key
      - name: Run tests
        run: mvn --batch-mode --update-snapshots test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
